# Generated by Django 4.2.7 on 2023-11-16 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_remove_compressedimage_compressed_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compressedimage',
            old_name='original_image',
            new_name='image',
        ),
    ]
