# Generated by Django 4.2.7 on 2023-11-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_rename_original_image_compressedimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='compressedimage',
            name='height',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='compressedimage',
            name='width',
            field=models.IntegerField(default=None),
        ),
    ]
