# Generated by Django 4.2.7 on 2023-11-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0006_remove_compressedimage_height_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compressedimage',
            old_name='image',
            new_name='file',
        ),
    ]
