# Generated by Django 4.2.7 on 2023-11-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0007_rename_image_compressedimage_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compressedimage',
            old_name='file',
            new_name='image',
        ),
    ]
